

#' Stochastic forward projections over an F grid
#'
#' Runs stochastic FLR forward projections with \code{ffwd()} over a grid of
#' fishing mortality values. By default, the grid is taken from
#' \code{fbar(brp)}, with the first value replaced by \code{Fmsy}. For each
#' F value, a corresponding \code{FLBRP}, \code{FLStock}, and \code{FLSR}
#' object is constructed, propagated over iterations, and projected forward
#' using recruitment deviances generated by \code{rlnormar1()}.
#'
#' The function is intended for exploring the emergent biomass process error
#' implied by an age-structured operating model under different constant
#' fishing mortality levels. The output can be passed to \code{pe_sampler()}
#' to obtain a data frame of depletion and process-error estimates.
#'
#' @param brp An \code{FLBRP} object containing biological reference points,
#'   stock-recruitment information, and an \code{fbar} grid.
#' @param Fgrid Optional numeric vector of fishing mortality values. If
#'   \code{NULL}, values are extracted from \code{fbar(brp)}.
#' @param sigmaR Numeric. Lognormal recruitment standard deviation.
#' @param rho Numeric. AR(1) autocorrelation coefficient for recruitment
#'   deviances.
#' @param nyears Integer. Number of projection years.
#' @param iters Integer. Number of stochastic iterations.
#' @param yrs.eval Optional integer. Number of final years intended for
#'   evaluation. If \code{NULL}, defaults to the second half of the projection.
#' @param parallel Logical. If \code{TRUE}, run projections in parallel using
#'   \pkg{doFuture}.
#' @param workers Optional integer. Number of parallel workers.
#' @param keep.stock Logical. Currently unused; retained for compatibility.
#' @param verbose Logical. If \code{TRUE}, print progress messages.
#'
#' @return An \code{FLStocks} object containing one projected \code{FLStock}
#'   per F value in the grid. The stocks are named using the corresponding
#'   F values.
#'
#' @details
#' The function constructs one \code{FLBRP} object per F value by replacing
#' \code{fbar(brp)} with a constant F. These objects are then converted to
#' \code{FLStock} and \code{FLSR} objects before stochastic forward projection.
#'
#' Recruitment deviances are generated once using \code{rlnormar1()} and then
#' passed to each \code{ffwd()} call. This allows the F scenarios to be compared
#' under the same recruitment-deviation structure.
#'
#' @examples
#' \dontrun{
#' data(ple4)
#' ple4 <- merge_catch(ple4)
#' bh <- srrTMB(
#'   as.FLSR(ple4, model = bevholt),
#'   spr0 = spr0y(ple4),
#'   r0 = NULL
#' )
#'
#' brp <- computeFbrp(ple4, bh, proxy = c("msy"))
#'
#' sim <- Fsim_grid(
#'   brp,
#'   sigmaR = 0.5,
#'   rho = 0.3,
#'   nyears = 100,
#'   iters = 20,
#'   parallel = TRUE,
#'   workers= 12
#' )
#'
#' class(sim)
#' names(sim)
#' }
#'
#' @export

Fsim_grid <- function(brp,
                      Fgrid = NULL,
                      sigmaR = 0.5,
                      rho = 0,
                      nyears = 100,
                      iters = 10,
                      yrs.eval = NULL,
                      parallel = FALSE,
                      workers = NULL,
                      progress = TRUE,
                      verbose = TRUE) {
  
  #------------------------------------------------------------
  # 1. Extract the F grid before modifying brp
  #------------------------------------------------------------
  
  fmsy <- an(refpts(brp)["msy","harvest"])
  if (is.null(Fgrid)) {
    Fgrid <- as.numeric(fbar(brp))
    Fgrid <- Fgrid[is.finite(Fgrid)]
    Fgrid[1] <- fmsy
  }
  
  
  
  nF <- length(Fgrid)
  
  
  
  # Now safe to reset fbar for constructing initial FLStock
  brps <- FLBRPs(lapply(Fgrid,function(x){
    brp0 <- brp
    fbar(brp0)[] <- x
    brp0
  }))
  
  names(brps) <- paste0("F",  round(an(Fgrid),2))
  
  stks <- FLStocks(lapply(brps,function(x){
    as(x, "FLStock")
  }))
  srs <- FLSRs(lapply(brps,function(x){
    as(x, "FLSR")
  }))
  
  
  if (nyears < 100) {
    stks <- window(stks, end = nyears + 1)
  }
  
  if (nyears > 100) {
    stks <- stf(stks, nyears - 100 + 1)
  }
  
  if (is.null(yrs.eval)) {
    yrs.eval <- ceiling(nyears / 2)
  }
  
  pyrs <- (nyears - yrs.eval + 1):nyears
  
  #------------------------------------------------------------
  # 2. Propagate stock and generate stochastic recruitment once
  #------------------------------------------------------------
  
  stks <- propagate(stks, iters)
  
  stks <- FLStocks(lapply(stks,function(x){
    stock.n(x)[2:(dim(x)[1]), 1] <-
      stock.n(x)[2:(dim(x)[1]), 1] *
      rlnorm(
        iters * (dim(x)[1] - 1),
        meanlog = -0.5 * sigmaR^2,
        sdlog = sigmaR
      )
    return(x)
  }))
  
  
  devs <- rlnormar1(
    rho = rho,
    year = 1:(nyears + 1),
    n = iters,
    meanlog = 0,
    sdlog = sigmaR,
    bias.correct = TRUE
  )
  
  #------------------------------------------------------------
  # 3. Inner function for one F candidate
  #------------------------------------------------------------
  
  run_one_F <- function(Fnow, i) {
    
    ftarget <- FLQuant(
      Fnow,
      dimnames = list(year = 2:(nyears + 1))
    )
    
    run <- ffwd(
      stks[[i]],
      sr = srs[[i]],
      fbar = ftarget,
      deviances = devs
    )
    
    run <- window(run, start = 2, end = nyears + 1)
    
    return(run)
  }
  
  #------------------------------------------------------------
  # 4. Run over all F candidates
  #------------------------------------------------------------
  
  if (progress) {
    requireNamespace("progressr")
  }
  
  if (parallel) {
    
    requireNamespace("foreach")
    requireNamespace("doFuture")
    requireNamespace("future")
    
    old_plan <- future::plan()
    on.exit(future::plan(old_plan), add = TRUE)
    
    if (is.null(workers)) {
      future::plan(future::multisession)
    } else {
      future::plan(future::multisession, workers = workers)
    }
    
    doFuture::registerDoFuture()
    
    if (progress) {
      
      res <- progressr::with_progress({
        
        p <- progressr::progressor(
          steps = length(Fgrid)
        )
        
        foreach::foreach(
          i = seq_along(Fgrid),
          .packages = c("FLCore")
        ) %dopar% {
          
          out <- run_one_F(Fgrid[i], i)
          
          p(sprintf(
            "F %s / %s",
            i,
            length(Fgrid)
          ))
          
          out
        }
      })
      
    } else {
      
      res <- foreach::foreach(
        i = seq_along(Fgrid),
        .packages = c("FLCore")
      ) %dopar% {
        run_one_F(Fgrid[i], i)
      }
    }
    
  } else {
    
    if (progress) {
      
      res <- progressr::with_progress({
        
        p <- progressr::progressor(
          steps = length(Fgrid)
        )
        
        lapply(seq_along(Fgrid), function(i) {
          
          out <- run_one_F(Fgrid[i], i)
          
          p(sprintf(
            "F %s / %s",
            i,
            length(Fgrid)
          ))
          
          out
        })
      })
      
    } else {
      
      res <- lapply(seq_along(Fgrid), function(i) {
        run_one_F(Fgrid[i], i)
      })
    }
  }
  
  #------------------------------------------------------------
  # 5. Collect output
  #------------------------------------------------------------
  
  res<- FLStocks(res)
  names(res) <-  paste0("F",  round(an(Fgrid),2))
  return(res)
}


#' Sample SPM-equivalent biomass process deviations from one projection
#'
#' Calculates biomass process deviations from a projected \code{FLStock}
#' by comparing the realised biomass transition with the deterministic
#' surplus-production expectation implied by \code{asem2spm()}.
#'
#' @param stk A projected \code{FLStock} object, usually one element from the
#'   \code{FLStocks} object returned by \code{Fsim_grid()}.
#' @param brp An \code{FLBRP} object used to derive the equivalent
#'   surplus-production parameters via \code{asem2spm()}.
#' @param biomass Character. Biomass metric to use. Either \code{"vb"} for
#'   vulnerable biomass or \code{"ssb"} for spawning-stock biomass.
#' @param eps Numeric. Small positive value used to avoid taking the logarithm
#'   of zero or negative predicted biomass.
#'
#' @return A list with elements:
#' \describe{
#'   \item{output}{A one-row \code{data.frame} with median F, process-error
#'   standard deviation, median B/Bmsy, and median B/B0.}
#'   \item{deviations}{An \code{FLQuant} of log biomass process deviations.}
#'   \item{ptpar}{The equivalent surplus-production parameters from
#'   \code{asem2spm()}.}
#'   \item{sigma}{Standard deviation of the sampled process deviations.}
#'   \item{bbmsy}{Biomass relative to Bmsy.}
#'   \item{bb0}{Median biomass relative to B0.}
#'   \item{biomass}{The biomass metric used.}
#' }
#'
#' @details
#' The process deviation is calculated as:
#'
#' \deqn{
#' \epsilon_t =
#' \log(B_{t+1}) -
#' \log\left[
#' B_t +
#' B_t \frac{r}{m - 1}
#' \left(
#' 1 - \left(\frac{B_t}{B_0}\right)^{m - 1}
#' \right)
#' - C_t
#' \right]
#' }
#'
#' where \eqn{r}, \eqn{m}, \eqn{B_0}, and \eqn{B_{MSY}} are obtained from
#' \code{asem2spm(brp, quant = biomass)}.
#'
#' This corresponds to sampling the residual process variation around the
#' SPM-equivalent biomass transition:
#'
#' \deqn{
#' B_{t+1} =
#' \left(B_t + P(B_t) - C_t\right) \exp(\epsilon_t)
#' }
#'
#' @examples
#' \dontrun{
#' sim <- Fsim_grid(
#'   brp,
#'   sigmaR = 0.5,
#'   rho = 0.3,
#'   nyears = 100,
#'   iters = 100
#' )
#'
#' one <- sample_proc_dev(
#'   stk = sim[[1]],
#'   brp = brp,
#'   biomass = "vb"
#' )
#'
#' one$output
#' one$sigma
#' }
#'
#' @export

sample_proc_dev <- function(stk, brp, biomass = c("vb", "ssb"), eps = 1e-12) {
  
  biomass <- match.arg(biomass)
  
  ptpar <- asem2spm(brp, quant = biomass)
  
  if (biomass == "vb") {
    bio <- vb(stk)
  } else if (biomass == "ssb") {
    bio <- ssb(stk)
  }
  
  bio0 <- bio[, -dim(bio)[2]]
  bio1 <- bio[, -1]
  cat0 <- catch(stk)[, -dim(bio)[2]]
  
  pred <- bio0 +
    bio0 * ptpar["r"] / (ptpar["m"] - 1) *
    (1 - (bio0 / ptpar["B0"])^(ptpar["m"] - 1)) -
    cat0
  
  pred[pred<eps] <- eps
  bio1[bio1<eps] <- eps
  
  deviations <- log(bio1) - log(pred)
  bbmsy <- an(mean(bio1)/ ptpar["Bmsy"])
  bb0 <- an(mean(bio1)/ ptpar["B0"])
  
  sigma <- sd(deviations)
  
  output <- data.frame(f=median(an(fbar(stk))), sigma=sigma,bbmsy=bbmsy,bb0)
  
  list(output=output,
       deviations = deviations,
       ptpar = ptpar,
       sigma =sigma,
       bbmsy = bio1/ptpar["Bmsy"],
       bb0 = median(bio1/ ptpar["B0"]),
       biomass = biomass
  )
}


#' Summarise biomass process error over an F grid
#'
#' Applies \code{sample_proc_dev()} to each projected stock in an
#' \code{FLStocks} object and returns a compact data frame of F, depletion,
#' and process-error estimates.
#'
#' @param stks An \code{FLStocks} object, usually returned by
#'   \code{Fsim_grid()}.
#' @param brp An \code{FLBRP} object used to derive equivalent SPM parameters.
#' @param biomass Character. Biomass metric to use. Either \code{"vb"} or
#'   \code{"ssb"}.
#' @param eps Numeric. Small positive value used to avoid logarithms of zero
#'   or negative predicted biomass.
#'
#' @return A \code{data.frame} with one row per F scenario and columns:
#' \describe{
#'   \item{f}{Median fishing mortality in the projected stock.}
#'   \item{sigma}{Sampled biomass process-error standard deviation.}
#'   \item{bbmsy}{Median biomass relative to Bmsy.}
#'   \item{bb0}{Median biomass relative to B0.}
#' }
#'
#' @details
#' This is a convenience wrapper around \code{sample_proc_dev()}. It is useful
#' for producing the main diagnostic relationship:
#'
#' \deqn{
#' \sigma_{proc} \sim B / B_{MSY}
#' }
#'
#' The output can be plotted directly to visualise how the emergent biomass
#' process error changes with stock depletion or fishing pressure.
#'
#' @examples
#' \dontrun{
#' data(ple4)
#' ple4 <- merge_catch(ple4)
#'
#' bh <- srrTMB(
#'   as.FLSR(ple4, model = bevholt),
#'   spr0 = spr0y(ple4),
#'   r0 = NULL
#' )
#'
#' brp <- computeFbrp(ple4, bh, proxy = c("msy"))
#'
#' sim <- Fsim_grid(
#'   brp,
#'   sigmaR = 0.5,
#'   rho = 0.3,
#'   nyears = 100,
#'   iters = 100,
#'   parallel = TRUE,
#'   workers = 4
#' )
#'
#' ps <- pe_sampler(sim, brp, biomass = "vb")
#'
#' head(ps)
#'
#' plot_pe(ps)
#' }
#' 
#' @export
pe_sampler <- function(stks, brp, biomass = c("vb", "ssb"), eps = 1e-12){
  biomass <- match.arg(biomass)
  out <- do.call(rbind,lapply(stks,function(x){
    sample_proc_dev(x, brp, biomass =   biomass , eps = 1e-12)$output 
  }))  
  rownames(out) <- 1:nrow(out) 
  out
}
#' Plot biomass process error against B/Bmsy
#'
#' Plots sampled biomass process error against biomass relative to Bmsy.
#' Optionally both axes can be normalised relative to a reference row,
#' typically row 1, which corresponds to the Fmsy scenario in Fsim_grid().
#'
#' @param ps data.frame returned by pe_sampler(), with columns sigma and bbmsy.
#' @param rel Logical. If TRUE, both B/Bmsy and sigma are divided by
#'   their reference values.
#' @param ref Integer. Reference row used for normalisation. Defaults to 1.
#' @param line Logical. Add line.
#' @param points Logical. Add points.
#' @param reverse_x Logical. Reverse x-axis.
#'
#' @return A ggplot object.
#'
#' @export
plot_pe <- function(ps,
                    rel = TRUE,
                    ref = 1,
                    line = TRUE,
                    points = TRUE,
                    reverse_x = FALSE) {
  
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required.")
  }
  
  if (!all(c("sigma", "bbmsy") %in% names(ps))) {
    stop("ps must contain columns: sigma and bbmsy.")
  }
  
  if (!ref %in% seq_len(nrow(ps))) {
    stop("ref must be a valid row number in ps.")
  }
  
  dat <- ps
  
  if (rel) {
    
    dat$xval <- dat$bbmsy
    dat$yval <- dat$sigma / dat$sigma[ref]
    
    xlab <- expression(B / B[MSY])
    ylab <- expression(sigma[proc] / sigma[proc][MSY])
    
  } else {
    
    dat$xval <- dat$bbmsy
    dat$yval <- dat$sigma
    
    xlab <- expression(B / B[MSY])
    ylab <- expression(sigma[proc])
  }
  
  dat_line <- dat[order(dat$xval), ]
  
  p <- ggplot2::ggplot(dat, ggplot2::aes(x = xval, y = yval)) +
    ggplot2::labs(x = xlab, y = ylab) +
    ggplot2::theme_bw()
  
  if (line) {
    p <- p +
      ggplot2::geom_line(
        data = dat_line,
        ggplot2::aes(x = xval, y = yval),
        linewidth = 0.8
      )
  }
  
  if (points) {
    p <- p + ggplot2::geom_point(size = 2,pch=21,fill="white")
  }
  
  if (rel) {
    p <- p +
      ggplot2::geom_vline(xintercept = 1, linetype = 2) +
      ggplot2::geom_hline(yintercept = 1, linetype = 2)
  } else {
    p <- p + ggplot2::geom_vline(xintercept = 1, linetype = 2)
  }
  
  if (reverse_x) {
    p <- p + ggplot2::scale_x_reverse()
  }
  
  p
}

#' Calculate vulnerable biomass from an FLBRP or FLStock object
#'
#' Calculates vulnerable biomass as the stock numbers-at-age multiplied by
#' stock weight-at-age and total selectivity. Total selectivity is defined as
#' the sum of landings and discards selectivity, scaled to a maximum of one.
#'
#' @param x An object with \code{stock.n}, \code{stock.wt},
#'   \code{landings.sel}, and \code{discards.sel} slots, typically an
#'   \code{FLBRP} or \code{FLStock} object.
#'
#' @return An \code{FLQuant} containing vulnerable biomass by year and
#'   iteration. Units are copied from \code{stock(x)}.
#'
#' @details
#' Vulnerable biomass is calculated as:
#'
#' \deqn{
#' VB_y = \sum_a N_{a,y} w_{a,y} s_a
#' }
#'
#' where \eqn{s_a} is total selectivity-at-age, calculated as
#' \code{landings.sel(x) + discards.sel(x)} and normalised to a maximum of one.
#'
#' This helper is useful when deriving an SPM-equivalent biomass quantity based
#' on vulnerable biomass rather than spawning biomass or total biomass.
#'
#' @examples
#' \dontrun{
#' vb <- vbbrp(brp)
#' plot(vb)
#' }
#'
#' @export
vbbrp <- function(x) {
  
  sel <- landings.sel(x) + discards.sel(x)
  sel <- sel / max(sel)
  
  vb <- quantSums(stock.n(x) %*% stock.wt(x) %*% sel)
  units(vb) <- units(stock(x))
  
  return(vb)
}

# vbbrp {{{
vbbrp <- function(x) {
            
  sel <- landings.sel(x) +discards.sel(x)
  sel <- sel/max(sel)
  vb <- quantSums(stock.n(x) %*% stock.wt(x) %*% sel)
  units(vb) <- units(stock(x))
  return(vb)
}


#' Merge catch into landings and remove discards
#'
#' Converts an \code{FLStock} object with total catch numbers into a
#' landings-only stock by assigning \code{catch.n} to \code{landings.n} and
#' setting \code{discards.n} to zero. Landings and discards weights are then
#' recomputed.
#'
#' @param stock An \code{FLStock} object.
#'
#' @return An \code{FLStock} object where all catch numbers are assigned to
#'   landings and discards are set to zero.
#'
#' @details
#' This is a convenience function for cases where catch should be treated as
#' landed catch, for example before forward projection or when preparing
#' simplified single-fleet inputs. The function modifies:
#'
#' \itemize{
#'   \item \code{landings.n(stock)}: set equal to \code{catch.n(stock)}
#'   \item \code{discards.n(stock)}: set to zero
#'   \item \code{landings(stock)}: recomputed with \code{computeLandings()}
#'   \item \code{discards(stock)}: recomputed with \code{computeDiscards()}
#' }
#'
#' @examples
#' \dontrun{
#' stock <- merge_catch(stock)
#'
#' # Check that discards have been removed
#' range(discards.n(stock))
#' discards(stock)
#' }
#'
#' @export
merge_catch <- function(stock) {
  
  landings.n(stock) <- catch.n(stock)
  discards.n(stock)[] <- 0
  
  landings(stock) <- computeLandings(stock)
  discards(stock) <- computeDiscards(stock)
  
  stock
}


#' asem2spm()
#' @param object An *FLBRP*
#' @param quant choose between vb and ssb 
#' @param spcurve if TRUE a data.frame is added
#' @param rel if TRUE ratios are produced for spcurve
#' @return prior means for r and m *FLPar*
#' @export
#' @examples
#' data(ple4)
#' ple4 <- merge_catch(ple4)
#' sr <- srrTMB(as.FLSR(ple4,model=bevholt),spr0=mean(spr0y(ple4)))
#' brp = brp(FLBRP(ple4,sr))
#' asem2spm(brp)
#' plot_pf(brp)
#' plot_pf(brp,rel=TRUE)

asem2spm <- function(object,quant=c("vb","ssb"),fmsy=NULL,rel=FALSE,spcurve=FALSE){
  quant = quant[1]
  pbrp = object
  
  if(is.null(fmsy)){
    fmsy = refpts(object)["msy","harvest"] 
  }
  fbar(brp) = FLQuant(c(0.,fmsy))
  MSY = an(catch(brp)[,2])
  
  if(quant=="vb") bio = vbbrp(brp)
  if(quant=="ssb") bio = ssb(brp)
  
  Hmsy=an(MSY/bio[,2])
  BmsyK =bio[,2]/bio[,1]
  mi = seq(0.0001,5,0.0001)
  m = mi[abs(mi^(-1/(mi-1))-an(BmsyK))==min(abs(mi^(-1/(mi-1))-an(BmsyK)))][1] 
  r = Hmsy*(m-1)/(1-1/m) 
  pars= FLPar(r=r,m=m,BmsyK =BmsyK,Hmsy=Hmsy,MSY=MSY ,Bmsy=bio[,2],B0=bio[,1],Fmsy=fmsy)  
  
  
  if(spcurve){
    if(quant=="vb")
      out = data.frame(Biomass=c(vbbrp(pbrp)),SP=c(catch(pbrp)),quant=quant)
    if(quant=="ssb") 
      out =data.frame(Biomass=c(ssb(pbrp)),SP=c(catch(pbrp)),quant=quant)
    
    if(rel){
      out$Biomass = out$Biomass/an(pars["B0"])  
      out$SP = out$SP/an(pars["MSY"])  
    }
  }
  
  if(!spcurve)
    return(pars)
  
  if(spcurve)
    return(list(pars=pars,curve=out))
  
} #}}}


#' Approximate age-structured equilibrium dynamics as a surplus production model
#'
#' Converts equilibrium reference-point information from an \code{FLBRP} object
#' into approximate Pella-Tomlinson surplus production model parameters. The
#' function derives the shape parameter \code{m} from the equilibrium ratio
#' \code{Bmsy / B0}, and derives the intrinsic productivity parameter \code{r}
#' from the harvest rate at MSY.
#'
#' The biomass quantity used for the approximation can be either vulnerable
#' biomass, \code{quant = "vb"}, or spawning-stock biomass, \code{quant = "ssb"}.
#' Optionally, the function can also return the equilibrium surplus production
#' curve implied by the supplied \code{FLBRP} object.
#'
#' @param object An \code{FLBRP} object containing equilibrium reference points
#'   and a grid of fishing mortality values.
#' @param quant Character. Biomass metric used to derive the SPM approximation.
#'   Options are \code{"vb"} for vulnerable biomass or \code{"ssb"} for
#'   spawning-stock biomass. Default is \code{"vb"}.
#' @param fmsy Optional fishing mortality at MSY. If \code{NULL}, the value is
#'   taken from \code{refpts(object)["msy", "harvest"]}.
#' @param rel Logical. If \code{TRUE} and \code{spcurve = TRUE}, return the
#'   surplus production curve in relative units, with biomass divided by
#'   \code{B0} and surplus production divided by \code{MSY}. Default is
#'   \code{FALSE}.
#' @param spcurve Logical. If \code{TRUE}, return a list containing both the
#'   estimated SPM parameters and a data frame of the equilibrium surplus
#'   production curve. If \code{FALSE}, only the parameter vector is returned.
#'   Default is \code{FALSE}.
#'
#' @return If \code{spcurve = FALSE}, an \code{FLPar} object with approximate
#'   surplus production parameters:
#' \describe{
#'   \item{\code{r}}{Intrinsic productivity parameter of the
#'     Pella-Tomlinson surplus production model.}
#'   \item{\code{m}}{Pella-Tomlinson shape parameter.}
#'   \item{\code{BmsyK}}{Equilibrium biomass ratio \code{Bmsy / B0}.}
#'   \item{\code{Hmsy}}{Harvest rate at MSY, calculated as
#'     \code{MSY / Bmsy}.}
#'   \item{\code{MSY}}{Maximum sustainable yield.}
#'   \item{\code{Bmsy}}{Biomass at MSY for the selected biomass metric.}
#'   \item{\code{B0}}{Unfished biomass for the selected biomass metric.}
#'   \item{\code{Fmsy}}{Fishing mortality at MSY.}
#' }
#'
#' If \code{spcurve = TRUE}, a list is returned with:
#' \describe{
#'   \item{\code{pars}}{The \code{FLPar} object described above.}
#'   \item{\code{curve}}{A data frame with columns \code{Biomass},
#'     \code{SP}, and \code{quant}. If \code{rel = TRUE}, \code{Biomass}
#'     is scaled by \code{B0} and \code{SP} by \code{MSY}.}
#' }
#'
#' @details
#' The function approximates the age-structured equilibrium yield curve with a
#' Pella-Tomlinson production function:
#'
#' \deqn{
#' P(B) =
#' B \frac{r}{m - 1}
#' \left[
#' 1 - \left(\frac{B}{B_0}\right)^{m - 1}
#' \right]
#' }
#'
#' The shape parameter \code{m} is solved numerically from the relationship:
#'
#' \deqn{
#' \frac{B_{MSY}}{B_0} = m^{-1 / (m - 1)}
#' }
#'
#' and \code{r} is calculated from:
#'
#' \deqn{
#' r = H_{MSY}
#' \frac{m - 1}{1 - 1 / m}
#' }
#'
#' where \code{Hmsy = MSY / Bmsy}. For \code{quant = "vb"}, \code{Bmsy}
#' and \code{B0} are based on vulnerable biomass calculated by
#' \code{vbbrp()}. For \code{quant = "ssb"}, they are based on
#' \code{ssb()}.
#'
#' This approximation is useful for deriving SPM-compatible prior means for
#' \code{r} and \code{m}, or for computing SPM-style process deviations from
#' age-structured stochastic projections.
#'
#' @examples
#' \dontrun{
#' data(ple4)
#'
#' ple4 <- merge_catch(ple4)
#'
#' sr <- srrTMB(
#'   as.FLSR(ple4, model = bevholt),
#'   spr0 = mean(spr0y(ple4))
#' )
#'
#' brp <- brp(FLBRP(ple4, sr))
#'
#' # Approximate SPM parameters using vulnerable biomass
#' pars_vb <- asem2spm(brp, quant = "vb")
#' pars_vb
#'
#' # Approximate SPM parameters using spawning biomass
#' pars_ssb <- asem2spm(brp, quant = "ssb")
#' pars_ssb
#'
#' # Return the surplus production curve in absolute units
#' sp <- asem2spm(brp, quant = "vb", spcurve = TRUE)
#' head(sp$curve)
#'
#' # Return the surplus production curve in relative units
#' sp_rel <- asem2spm(brp, quant = "vb", spcurve = TRUE, rel = TRUE)
#' head(sp_rel$curve)
#'
#' plot_pf(brp)
#' plot_pf(brp, rel = TRUE)
#' }
#'
#' @export
asem2spm <- function(object,
                     quant = c("vb", "ssb"),
                     fmsy = NULL,
                     rel = FALSE,
                     spcurve = FALSE) {
  
  quant <- match.arg(quant)
  
  pbrp <- object
  brp <- object
  
  if (is.null(fmsy)) {
    fmsy <- refpts(object)["msy", "harvest"]
  }
  
  fbar(brp) <- FLQuant(c(0, fmsy))
  
  MSY <- an(catch(brp)[, 2])
  
  if (quant == "vb") {
    bio <- vbbrp(brp)
  } else if (quant == "ssb") {
    bio <- ssb(brp)
  }
  
  Hmsy <- an(MSY / bio[, 2])
  BmsyK <- bio[, 2] / bio[, 1]
  
  mi <- seq(0.0001, 5, 0.0001)
  
  m <- mi[
    abs(mi^(-1 / (mi - 1)) - an(BmsyK)) ==
      min(abs(mi^(-1 / (mi - 1)) - an(BmsyK)))
  ][1]
  
  r <- Hmsy * (m - 1) / (1 - 1 / m)
  
  pars <- FLPar(
    r = r,
    m = m,
    BmsyK = BmsyK,
    Hmsy = Hmsy,
    MSY = MSY,
    Bmsy = bio[, 2],
    B0 = bio[, 1],
    Fmsy = fmsy
  )
  
  if (spcurve) {
    
    if (quant == "vb") {
      out <- data.frame(
        Biomass = c(vbbrp(pbrp)),
        SP = c(catch(pbrp)),
        quant = quant
      )
    } else if (quant == "ssb") {
      out <- data.frame(
        Biomass = c(ssb(pbrp)),
        SP = c(catch(pbrp)),
        quant = quant
      )
    }
    
    if (rel) {
      out$Biomass <- out$Biomass / an(pars["B0"])
      out$SP <- out$SP / an(pars["MSY"])
    }
    
    return(list(pars = pars, curve = out))
  }
  
  return(pars)
}

#' plot_pf()
#' 
#' plots production functions 
#' @param object An *FLBRP*
#' @param quant choose between vb and ssb or both
#' @param fmsy default if Fmsy
#' @param rel if TRUE ratios are produced for spcurve
#' @return ggplot
#' @export
#' @examples
#' data(ple4)
#' ple4 <- merge_catch(ple4)
#' sr <- srrTMB(as.FLSR(ple4,model=bevholtSV),spr0=mean(spr0y(ple4)))
#' brp = brp(FLBRP(ple4,sr))
#' asem2spm(brp)[1:4]
#' plot_pf(brp)
#' plot_pf(brp,rel=TRUE)
plot_pf <- function(object,quant=c("vb","ssb"),fmsy=NULL,rel=FALSE){
  
  pf = function(asem,quant,rel=FALSE){
    quant = quant[1]
    bio = asem$curve$Biomass
    r= c(asem$pars["r"])
    m= c(asem$pars["m"])
    k= ifelse(rel,1,c(asem$pars["B0"]))
    SP = bio*r/(m-1)*(1-(bio/k)^(m-1))
    if(rel) SP= SP/max(SP,na.rm = T)
    return(data.frame(Biomass=bio,SP=SP,quant=quant,method="spm"))
  }
  
  asem = asem2spm(object,quant=quant[1],fmsy=fmsy,spcurve = TRUE,rel=rel)
  
  y = an(asem$pars["MSY"])
  x = an(asem$pars["Bmsy"])
  
  if(rel){
    x = an(asem$pars["BmsyK"])
    y =1
  }
  xy = data.frame(x=x,y=y,method="spm",quant=quant[1])
  df = rbind(data.frame(asem$curve,method="asem"),pf(asem,quant[1],rel=rel))
  
  if(length(quant)>1){
    asem = asem2spm(object,quant=quant[2],fmsy=fmsy,spcurve = TRUE,rel=rel)
    y = an(asem$pars["MSY"])
    x = an(asem$pars["Bmsy"])
    if(rel){
      y =1
      x = an(asem$pars["BmsyK"])
    }
    xy = rbind(xy,data.frame(x=x,y=y,method="spm",quant=quant[2]))
    df = rbind(df,data.frame(asem$curve,method="asem"),pf(asem,quant[2],rel=rel)) 
    
  }
  
  p = ggplot(df,aes(Biomass,SP,linetype=method,col=quant))+
    geom_line(linewidth=0.9)+
    geom_segment(data= xy,aes(x =x,y=0,xend = x, yend = y),linetype=2)+
    theme_bw()+theme(legend.title = element_blank())+
    ylab("Surplus Production")+
    xlab(ifelse(!rel,"Biomas",expression(B/B[0])))+
    scale_x_continuous(expand = expansion(mult = c(0, .05)),labels=human_numbers, limits=c(0, NA))+
    scale_y_continuous(expand = expansion(mult = c(0, .1)))
  return(p)
  
}

